### ISSUE TITLE
Crashes with use of the 3.65 enzo

### ISSUE THREAD

**Issue by Korori03** [motoharu-gosuto/psvgamesd#36]
It was working on 3.60 enzo and recently updated. Just wondering if anyone figured out a fix for this or patiently wait for the update :)

**Comment by RY0M43CH1Z3N** [comment]
Try it TheFloW version: https://github.com/TheOfficialFloW/gamecard-microsd/releases

**Comment by GrayJack** [comment]
gamecard-microsd have nothing to do with this project.
This one allows to dump gamecards and run gamecards dumps, gamecard-microsd allows to use a gamecard-to-sd adapter as a storage.

I can confirm that this is not working on 3.65 enso

**Comment by Korori03** [comment]
Thank you, just wanted to make sure I covered everything.
